[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.coverage.report]
exclude_lines = [
    # re-enable standard pragma
    "pragma: cover",
    # unreachable branches
    "raise InvalidBranchException"
]
